apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: danalambert/cs-field-guide_django
        ports:
        - containerPort: 81
        command: ["/cs-field-guide/csfieldguide/docker-development-entrypoint.sh"]
        env:
        - name: DATABASE_URL
          value: postgres://postgres@postgres:5434/postgres
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.local
        - name: INCLUDE_INCONTEXT_L10N
          value: "False"
        volumeMounts:
        - mountPath: /cs-field-guide
          name: django-claim0
      volumes:
      - name: django-claim0
        persistentVolumeClaim:
          claimName: django-claim0
