apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: uccser/nginx-with-gulp:1.15.5 #danalambert/cs-field-guide_nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/
          name: nginx-app
        - mountPath: /app/node_modules
          name: nginx-nodemodules
      volumes:
      - name: nginx-app
        hostPath:
          path: /home/docker/cs-field-guide/csfieldguide
      - name: nginx-nodemodules
        hostPath:
          path: /home/docker/cs-field-guide/csfieldguide/node_modules
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: NodePort
---
